# Generated by Django 3.2.12 on 2022-03-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20220307_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='mturk_hit_expiration',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='mturk_hit_id',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='mturk_hit_status',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='mturk_hit_title',
        ),
        migrations.AddField(
            model_name='task',
            name='mturk_hit_expiration',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='mturk_hit_id',
            field=models.CharField(editable=False, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='mturk_hit_status',
            field=models.CharField(editable=False, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='mturk_hit_title',
            field=models.CharField(editable=False, max_length=128, null=True),
        ),
    ]
