# Generated by Django 3.2.12 on 2022-03-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20220307_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='mturk_batch_id',
            field=models.CharField(editable=False, max_length=32, null=True),
        ),
    ]
