# Generated by Django 3.2.12 on 2022-03-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_batch_mturk_batch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='mturk_assignment_id',
            field=models.CharField(editable=False, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='mturk_assignment_status',
            field=models.CharField(editable=False, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='mturk_worker_accept_time',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='mturk_worker_feedback',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='mturk_worker_id',
            field=models.CharField(editable=False, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='mturk_worker_submit_time',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
