# Generated by Django 3.2.12 on 2022-04-19 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20220307_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='manual_list',
            field=models.JSONField(blank=True, default=[]),
        ),
        migrations.AddField(
            model_name='task',
            name='manual_list',
            field=models.JSONField(blank=True, default=[]),
        ),
    ]
