# Generated by Django 3.2.12 on 2022-04-19 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20220419_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='manual_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='task',
            name='manual_list',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
