# Generated by Django 3.2.12 on 2022-04-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20220419_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_fixed',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_indoor',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='mturk_worker_status',
            field=models.CharField(editable=False, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='people_count',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
