# Generated by Django 3.2.12 on 2022-04-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20220419_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='person_view',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='is_fixed',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='is_indoor',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='people_count',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
