# Generated by Django 3.2.13 on 2022-05-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_auto_20220419_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='mturk_hit_number_of_assignment_available',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='mturk_hit_number_of_assignment_completed',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='mturk_hit_number_of_assignment_pending',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
