# Generated by Django 3.2.13 on 2022-05-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_auto_20220524_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='video_duration',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='video_title',
            field=models.CharField(blank=True, editable=False, max_length=1024, null=True),
        ),
    ]
